# This file is used as dynamicconfig override for "activepassive_to_activeactive" replication simulation scenario configured via simulation/replication/testdata/replication_simulation_activepassive_to_activeactive.yaml
system.writeVisibilityStoreName:
  - value: "db"
system.readVisibilityStoreName:
  - value: "db"
history.replicatorTaskBatchSize:
  - value: 25
    constraints: {}
frontend.failoverCoolDown:
  - value: 5s
history.ReplicationTaskProcessorStartWait: # default is 5s. repl task processor sleeps this much before processing received messages.
  - value: 10ms
history.standbyTaskMissingEventsResendDelay:
  - value: 5s
history.standbyTaskMissingEventsDiscardDelay:
  - value: 10s
history.standbyClusterDelay:
  - value: 10s
history.enableTransferQueueV2:
  - value: true
history.enableTimerQueueV2:
  - value: true
frontend.enableActiveClusterSelectionPolicyInStartWorkflow:
  - value: true
