# This workflow runs replication simulaton scenarios via GithubActions matrix strategy.
# Scenarios are defined in the `simulation/replication/testdata/replication_simulation_<scenario>.yaml` files.
name: Replication Simulation
on:
  push:
  pull_request:

jobs:
  replication-simulation:
    name: Replication Simulation (${{ matrix.scenario }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - activeactive
          - activeactive_same_wfid
          - activeactive_cron
          - activeactive_regional_failover
          - activeactive_regional_failover_start_same_wfid
          - activeactive_regional_failover_start_same_wfid_2
          - activepassive_to_activeactive
          - clusterredirection
          - reset
          - default

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4'

      - name: Run simulation
        uses: nick-fields/retry@v3
        with:
          max_attempts: 2
          timeout_minutes: 20
          command: |
            ./simulation/replication/run.sh ${{ matrix.scenario }}

      - name: Upload test logs
        uses: actions/upload-artifact@v4
        with:
          name: replication-${{ matrix.scenario }}-test.log
          path: ./test.log
